name = "MMDeweighting"
uuid = "9df87fff-401a-4135-9240-c4d948f02a67"
authors = ["Qiang-Heng"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
